# Site settings
title: Barbara Schwarzl
email: b.schwarzl.autor@A1.net
facebook: https://www.facebook.com/schreibendeApothekerin
description: Die schreibende Apothekerin und ihre BÃ¼cher
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://barbaraschwarzl.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

paginate: 5

author: Barbara Schwarzl

plugins:
  - jekyll-paginate

collections:
  books:
    output: true